// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BankAccount struct {
	Owner   *Person `json:"owner"`
	Balance float64 `json:"balance"`
	ID      string  `json:"id"`
}

type BankApplication struct {
	Applicant      *PersonInput `json:"applicant"`
	OpeningDeposit *float64     `json:"openingDeposit,omitempty"`
}

type PersonInput struct {
	Name string `json:"name"`
	Age  *int   `json:"age,omitempty"`
}

type CreateBankAccountResponse struct {
	Code    int    `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}
