// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BankAccount struct {
	Owner   *Person `json:"owner"`
	Balance float64 `json:"balance"`
	ID      string  `json:"id"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type PersonInput struct {
	Name string `json:"name"`
	Age  *int   `json:"age,omitempty"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateBankAccountResponse struct {
	Code    int    `json:"code"`
	Success bool   `json:"success"`
	Message string `json:"message"`
}
